#cloud-config
package_update: true
package_upgrade: true
packages:
    - python3-pip
    - build-essential
    - unzip
    - jq
    - git
    - ssh-import-id
users:
  - name: ilab
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh_public_key}
    lock_passwd: true