#cloud-config
users:
  - name: ilab
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh_public_key}
    lock_passwd: true

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - build-essential

# Ensure SSH service is running
runcmd:
  - systemctl enable ssh
  - systemctl start ssh
  - usermod -aG sudo ilab

# Set timezone
timezone: UTC

# Configure SSH
ssh_pwauth: false
disable_root: true